version: '3'

services:
   master:
     build: ./jenkins-master
     ports:
       - "50000:50000"
     volumes:
       - jenkins-log:/var/log/jenkins
       - jenkins-data:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - /var/lib/docker:/var/lib/docker  
     networks:
       - jenkins-net
   nginx:
     build: ./jenkins-nginx
     ports:
       - "80:80"
     networks:
       - jenkins-net

volumes:
  jenkins-data:
  jenkins-log:

networks:
  jenkins-net:

